id: P009557
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W24824
  title: དུངས་ཞེན་དཀར་པོ།
  author: ''
  volumes:
    69b7366e67484b768b40493958d571d4:
      image_group_id: I1KG22748
      title: ''
      volume_number: 1
      total_pages: 166
      base_file: v001.txt
